# MIT License
#
# Copyright (c) 2022 Dilina Dehigama and EASE Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
name: Run scheduled experiments (New)

on: push
  
jobs:

  clean_up:
    name: Clean-up workspace
    runs-on: self-hosted
    env:
      working-directory: ./src
    steps:
      - name: 'Cleanup build folder'
        run: |
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true

  build_client:
    name: Build framework
    needs: clean_up
    runs-on: self-hosted
    env:
      working-directory: ./src
    steps:
      - name: Configure AWS credentials using EASE lab account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libsnmp-dev build-essential zip docker.io

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: continuous-benchmarking-new

      - name: Check syntax
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          working-directory: ${{env.working-directory}}
          args: --timeout 5m --skip-dirs raw-code
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Clean and build client binary
        working-directory: ${{env.working-directory}}
        run: |
          chmod +x build.sh
          ./build.sh

  run_warm_experiments:
    name: Run warm function experiments
    runs-on: self-hosted
    env:
      working-directory: ./src
    steps:
      - name: AWS Warm Function Invocation - Baseline
        working-directory: ${{env.working-directory}}
        run: ./stellar -a 356764711652 -o latency-samples -c ../continuous-benchmarking/experiments/warm-function-invocations/warm-baseline-aws.json -db -w

  run_cold_experiments:
    name: Run cold function experiments
    needs: run_warm_experiments
    runs-on: self-hosted
    env:
      working-directory: ./src
    steps:
    
      - name: AWS Cold Function Invocation - Baseline
        working-directory: ${{env.working-directory}}
        run: ./stellar -a 356764711652 -o latency-samples -c ../continuous-benchmarking/experiments/cold-function-invocations/cold-baseline-aws.json -db
